packages:
  install:
    system:
      - 7zip
      - age
      - bash
      - bat
      - biber
      - brightnessctl
      - brightnessctl
      - chezmoi
      - cmatrix
      - cowsay
      - cups
      - cups-pdf
      - fd
      - fd
      - ffmpeg
      - fish
      - fortune-mod
      - fprintd
      - fuzzel
      - fwupd
      - fzf
      - fzf
      - gdm
      - ghostty
      - git
      - gnome-font-viewer
      - gnome-keyring
      - go
      - gwenview
      - hyprpicker
      - imagemagick
      - inkscape
      - interception-caps2esc
      - interception-tools
      - jq
      - kitty
      - libdvdcss
      - lolcat
      - mako
      - man-db
      - neovim
      - net-tools
      - niri
      - nnn
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - npm
      - okular
      - org.freedesktop.secrets
      - pavucontrol
      - pipewire
      - pipewire-pulse
      - plasma
      - playerctl
      - plocate
      - polkit-kde-agent
      - poppler
      - power-profiles-daemon
      - python-pynvim
      - resvg
      - ripgrep
      - ripgrep
      - rsync
      - rustup
      - seahorse
      - sg3_utils
      - swaybg
      - swayidle
      - swaylock
      - syncthing
      - system-config-printer
      - systemd-resolvconf
      - texlive
      - thunar
      - thunderbird
      - tmux
      - trash-cli
      - tree
      - ttf-font-awesome
      - ttf-inconsolata
      - ttf-inconsolata-nerd
      - waybar
      - wget
      - wine
      - wine-mono
      - winetricks
      - wireplumber
      - wl-clipboard
      - xdg-desktop-portal-gnome
      - xwayland-satellite
      - yazi
      - zip
      - zoxide
    flatpak:
      - com.discordapp.Discord
      - com.github.tchx84.Flatseal
      - io.github.ungoogled_software.ungoogled_chromium
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.mozilla.firefox
      - org.signal.Signal
      - org.zotero.Zotero
    aur:
      - aseprite
      - chezmoi_modify_manager
      - clipman
      - pam-fprint-grosshack
      - todotxt
      - yay
  remove:
    system:
      - firefox
    # NOTE: aur.remove is not supported, but flatpak.remove is
